CREATE OR REPLACE FUNCTION GET_NB_WORKERS(FACTORY_ID NUMBER) RETURN NUMBER AS
  NB_WORKERS NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO NB_WORKERS
  FROM (
    SELECT id FROM WORKERS_FACTORY_1 WHERE factory_id = FACTORY_ID AND last_day IS NULL
    UNION ALL
    SELECT worker_id FROM WORKERS_FACTORY_2 WHERE factory_id = FACTORY_ID AND end_date IS NULL
  );
  RETURN NB_WORKERS;
END;


CREATE OR REPLACE FUNCTION GET_NB_BIG_ROBOTS RETURN NUMBER AS
  BIG_ROBOTS_COUNT NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO BIG_ROBOTS_COUNT
  FROM (
    SELECT robot_id
    FROM ROBOTS_HAS_SPARE_PARTS
    GROUP BY robot_id
    HAVING COUNT(spare_part_id) > 3
  );
  RETURN BIG_ROBOTS_COUNT;
END;


CREATE OR REPLACE FUNCTION GET_BEST_SUPPLIER RETURN VARCHAR2 IS
  BEST_SUPPLIER_NAME VARCHAR2(100);
BEGIN
  SELECT name INTO BEST_SUPPLIER_NAME FROM BEST_SUPPLIERS WHERE ROWNUM = 1;
  RETURN BEST_SUPPLIER_NAME;
END;
